version: "3.8"
services:
  db:
    build: ./db
    image: db
    ports:
      - "3306:3306"
    volumes:
      - ./db/logs:/var/log/mysql
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
        read_only: false
    environment:
      MYSQL_USER: ${MYSQL_USER?MYSQL_USER not passed}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?MYSQL_PASSWORD not passed}
      MYSQL_DATABASE: ${MYSQL_DATABASE?MYSQL_DATABASE not passed}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD?MYSQL_PASSWORD not passed}
      TZ: ${TZ?TZ not passed}

volumes:
  mysql_data:
